repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - "-rn"  # Only display messages
          - "-sn"  # Don't display the score
          - "--rcfile=4 - Nivel 4 - Introdução ao Design de Código/Arquitetura de Software e Padrão MVC/.pylintrc"  # Link to your config file
          - "--load-plugins=pylint.extensions.docparams"  # Load an extension
